name: Node

on:
  push:
    branches:
      - !gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12' ]
    steps:
      - uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - name: (tmp) dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      # - name: deploy docs
      #   if: GITHUB_REF == 'refs/heads/master' && matrix.node == '12'
      #   uses: maxheld83/ghpages@v0.2.1
      #   env:
      #     GH_PAT: ${{ secrets.GH_PAT }}
      #     BUILD_DIR: docs


